name: Continuous Integration

on:
  push:
    branches:
      - 'features/*'
    
jobs:

  test:
    name: Run unit tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: falti/dotenv-action@v0.2.5
        id: dotenv
        with:
          path: ./config/dev.env
#      - name: Hello world
#        run: echo Hello world $FIRST_NAME $middle_name $Last_Name ${{ steps.dotenv.outputs.version }}!
#        env:
#          FIRST_NAME: Mona
#          middle_name: The
#          Last_Name: Octocat
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Run unit tests
        run: mvn -B verify
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          files: ./target/surefire-reports/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
      - uses: jwgmeligmeyling/pmd-github-action@master
        if: always()
        with:
          path: '**/pmd.xml'
      - uses: jwgmeligmeyling/spotbugs-github-action@master
        if: always()
        with:
          path: '**/spotbugsXml.xml'
      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: jacoco-report
          path: target/site/jacoco/
      - uses: codecov/codecov-action@v1
        if: always()
        with:
          file: target/site/jacoco/jacoco.xml
          fail_ci_if_error: false
      - name: Build Docker image
        run: docker build --file ./src/main/docker/Dockerfile --tag ${{ steps.dotenv.outputs.DOCKER_REPOSITORY}}/${{ steps.dotenv.outputs.APP}}-${{ steps.dotenv.outputs.APP_MODULE}}:latest .